version: '4.1'

services:
  froneus-mysql:
    image: mysql:8.0
    container_name: froneus_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: froneus
      MYSQL_USER: froneusProject
      MYSQL_PASSWORD: 123456%%%
    ports:
      - "3306:3306"
    volumes:
      - C:\froneus\mysql:/var/lib/mysql
    networks:
      - mynet
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"    # puerto AMQP
      - "15672:15672"  # puerto de la consola de administración
    networks:
      - mynet

  froneus-java:
    build:
      context: C:\Users\Maxi\Desktop\froneus\froneus
      dockerfile: Dockerfile
    container_name: froneus_java_app
    ports:
      - "8080:8080"
    depends_on:
      - froneus-mysql
      - rabbitmq
    networks:
      - mynet  

networks:
      mynet:
  
